language: node_js
node_js:
  - node

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - yarn --version
install:
  - skip #I'm using Yarn Zero-Installs
script:
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GH_TOKEN
  committer_from_gh: true
  target_branch: $TRAVIS_BRANCH
  on:
    branch: project-travis
