language: node_js
node_js:
  - node

before_install:
  - yarn policies set-version berry
install:
  - skip #I'm using Yarn Zero-Installs
script:
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GH_TOKEN
  committer_from_gh: true
  target_branch: $TRAVIS_BRANCH
  local_dir: ./dist
  on:
    branch: $TRAVIS_BRANCH
