language: node_js
node_js:
  - node

before_install:
  - yarn policies set-version latest
  - yarn -v
  - yarn set version berry
  - yarn -v
  - rm -f .yarnrc
  - yarn -v
  - yarn set version latest
  - yarn -v
  - ls -alhF
  - yarn -v
install:
  - skip #I'm using Yarn Zero-Installs
script:
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GH_TOKEN
  committer_from_gh: true
  target_branch: $TRAVIS_BRANCH
  on:
    branch: project-travis
